/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCadastrosRouteRouteImport } from './routes/_authenticated/cadastros/route'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedCadastrosColaboradoresRouteImport } from './routes/_authenticated/cadastros/colaboradores'
import { Route as AuthenticatedCadastrosEquipamentosRouteImport } from './routes/_authenticated/cadastros/equipamentos'
import { Route as AuthenticatedCadastrosSupervisoresRouteImport } from './routes/_authenticated/cadastros/supervisores'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios/index'
import { Route as AuthenticatedRelatoriosIdRouteImport } from './routes/_authenticated/relatorios/$id'
import { Route as AuthenticatedRelatoriosNovoRouteImport } from './routes/_authenticated/relatorios/novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCadastrosRouteRoute =
  AuthenticatedCadastrosRouteRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosColaboradoresRoute =
  AuthenticatedCadastrosColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedCadastrosRouteRoute,
  } as any)
const AuthenticatedCadastrosEquipamentosRoute =
  AuthenticatedCadastrosEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedCadastrosRouteRoute,
  } as any)
const AuthenticatedCadastrosSupervisoresRoute =
  AuthenticatedCadastrosSupervisoresRouteImport.update({
    id: '/supervisores',
    path: '/supervisores',
    getParentRoute: () => AuthenticatedCadastrosRouteRoute,
  } as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosIdRoute =
  AuthenticatedRelatoriosIdRouteImport.update({
    id: '/relatorios/$id',
    path: '/relatorios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosNovoRoute =
  AuthenticatedRelatoriosNovoRouteImport.update({
    id: '/relatorios/novo',
    path: '/relatorios/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof AuthenticatedCadastrosRouteRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/cadastros/colaboradores': typeof AuthenticatedCadastrosColaboradoresRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/supervisores': typeof AuthenticatedCadastrosSupervisoresRoute
  '/relatorios/$id': typeof AuthenticatedRelatoriosIdRoute
  '/relatorios/novo': typeof AuthenticatedRelatoriosNovoRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cadastros': typeof AuthenticatedCadastrosRouteRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/cadastros/colaboradores': typeof AuthenticatedCadastrosColaboradoresRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/supervisores': typeof AuthenticatedCadastrosSupervisoresRoute
  '/relatorios/$id': typeof AuthenticatedRelatoriosIdRoute
  '/relatorios/novo': typeof AuthenticatedRelatoriosNovoRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRouteRouteWithChildren
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/cadastros/colaboradores': typeof AuthenticatedCadastrosColaboradoresRoute
  '/_authenticated/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/_authenticated/cadastros/supervisores': typeof AuthenticatedCadastrosSupervisoresRoute
  '/_authenticated/relatorios/$id': typeof AuthenticatedRelatoriosIdRoute
  '/_authenticated/relatorios/novo': typeof AuthenticatedRelatoriosNovoRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cadastros'
    | '/painel'
    | '/cadastros/colaboradores'
    | '/cadastros/equipamentos'
    | '/cadastros/supervisores'
    | '/relatorios/$id'
    | '/relatorios/novo'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cadastros'
    | '/painel'
    | '/cadastros/colaboradores'
    | '/cadastros/equipamentos'
    | '/cadastros/supervisores'
    | '/relatorios/$id'
    | '/relatorios/novo'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/cadastros'
    | '/_authenticated/painel'
    | '/_authenticated/cadastros/colaboradores'
    | '/_authenticated/cadastros/equipamentos'
    | '/_authenticated/cadastros/supervisores'
    | '/_authenticated/relatorios/$id'
    | '/_authenticated/relatorios/novo'
    | '/_authenticated/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/colaboradores': {
      id: '/_authenticated/cadastros/colaboradores'
      path: '/colaboradores'
      fullPath: '/cadastros/colaboradores'
      preLoaderRoute: typeof AuthenticatedCadastrosColaboradoresRouteImport
      parentRoute: typeof AuthenticatedCadastrosRouteRoute
    }
    '/_authenticated/cadastros/equipamentos': {
      id: '/_authenticated/cadastros/equipamentos'
      path: '/equipamentos'
      fullPath: '/cadastros/equipamentos'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipamentosRouteImport
      parentRoute: typeof AuthenticatedCadastrosRouteRoute
    }
    '/_authenticated/cadastros/supervisores': {
      id: '/_authenticated/cadastros/supervisores'
      path: '/supervisores'
      fullPath: '/cadastros/supervisores'
      preLoaderRoute: typeof AuthenticatedCadastrosSupervisoresRouteImport
      parentRoute: typeof AuthenticatedCadastrosRouteRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/$id': {
      id: '/_authenticated/relatorios/$id'
      path: '/relatorios/$id'
      fullPath: '/relatorios/$id'
      preLoaderRoute: typeof AuthenticatedRelatoriosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/novo': {
      id: '/_authenticated/relatorios/novo'
      path: '/relatorios/novo'
      fullPath: '/relatorios/novo'
      preLoaderRoute: typeof AuthenticatedRelatoriosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCadastrosRouteRouteChildren {
  AuthenticatedCadastrosColaboradoresRoute: typeof AuthenticatedCadastrosColaboradoresRoute
  AuthenticatedCadastrosEquipamentosRoute: typeof AuthenticatedCadastrosEquipamentosRoute
  AuthenticatedCadastrosSupervisoresRoute: typeof AuthenticatedCadastrosSupervisoresRoute
}

const AuthenticatedCadastrosRouteRouteChildren: AuthenticatedCadastrosRouteRouteChildren =
  {
    AuthenticatedCadastrosColaboradoresRoute:
      AuthenticatedCadastrosColaboradoresRoute,
    AuthenticatedCadastrosEquipamentosRoute:
      AuthenticatedCadastrosEquipamentosRoute,
    AuthenticatedCadastrosSupervisoresRoute:
      AuthenticatedCadastrosSupervisoresRoute,
  }

const AuthenticatedCadastrosRouteRouteWithChildren =
  AuthenticatedCadastrosRouteRoute._addFileChildren(
    AuthenticatedCadastrosRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRouteRoute: typeof AuthenticatedCadastrosRouteRouteWithChildren
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedRelatoriosIdRoute: typeof AuthenticatedRelatoriosIdRoute
  AuthenticatedRelatoriosNovoRoute: typeof AuthenticatedRelatoriosNovoRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRouteRoute:
    AuthenticatedCadastrosRouteRouteWithChildren,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedRelatoriosIdRoute: AuthenticatedRelatoriosIdRoute,
  AuthenticatedRelatoriosNovoRoute: AuthenticatedRelatoriosNovoRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
